### ISSUE TITLE
Cannot install Mojo::Phantom

### ISSUE THREAD

**Issue by dmanto** [jberger/Mojo-Phantom#10]
On ubuntu mate 16.04, 64 bits, perl v5.24.0 (also tried v5.22.1), and Phantomjs v2.1.1, installed whith:

`$> sudo apt-get install phantomjs
`

trying to install Mojo::Phantom:

`$> cpanm Mojo::Phantom
`

fails, with following log:

> cpanm (App::cpanminus) 1.7040 on perl 5.024000 built for x86_64-linux-thread-multi
> Work directory is /home/daniel/.cpanm/work/1464480846.2369
> You have make /usr/bin/make
> You have /usr/bin/wget
> You have /bin/tar: tar (GNU tar) 1.28
> Copyright © 2014 Free Software Foundation, Inc.
> License GPLv3+: GPL de GNU versión 3 o posterior http://gnu.org/licenses/gpl.html
> Esto es software libre: usted es libre de cambiarlo y redistribuirlo.
> No hay NINGUNA GARANTÍA, hasta donde permite la ley.
> 
> Escrito por John Gilmore y Jay Fenlason.
> You have /usr/bin/unzip
> Searching Mojo::Phantom () on cpanmetadb ...
> --> Working on Mojo::Phantom
> Fetching http://www.cpan.org/authors/id/J/JB/JBERGER/Mojo-Phantom-0.03.tar.gz
> -> OK
> Unpacking Mojo-Phantom-0.03.tar.gz
> Entering Mojo-Phantom-0.03
> Checking configure dependencies from META.json
> Checking if you have IPC::Cmd 0 ... Yes (0.92)
> Checking if you have Module::Build::Tiny 0.007 ... Yes (0.039)
> Configuring Mojo-Phantom-0.03
> Running Build.PL
> Creating new 'Build' script for 'Mojo-Phantom' version '0.03'
> -> OK
> Checking dependencies from MYMETA.json ...
> Checking if you have Mojolicious 6.0 ... Yes (6.62)
> Checking if you have Test::Mojo::WithRoles 0 ... Yes (0.02)
> Checking if you have Test::More 0 ... Yes (1.001014)
> Checking if you have JavaScript::Value::Escape 0 ... Yes (0.07)
> Checking if you have Role::Tiny 0 ... Yes (2.000003)
> Building and testing Mojo-Phantom-0.03
> cp lib/Test/Mojo/Role/Phantom.pm blib/lib/Test/Mojo/Role/Phantom.pm
> cp lib/Mojo/Phantom.pm blib/lib/Mojo/Phantom.pm
> cp lib/Mojo/Phantom/Process.pm blib/lib/Mojo/Phantom/Process.pm
> t/basic.t ...... ok
> 
> ```
> #   Failed test 'don't get here'
> #   at (eval 94) line 1.
> ```
> 
> Use of uninitialized value $error in scalar chomp at t/exception.t line 51.
> 
> ```
> #   Failed test 'got the right error'
> #   at t/exception.t line 52.
> #                   undef
> #     doesn't match '(?^:PHANTOM ERROR.*dozNotExistz)'
> # Looks like you failed 2 tests of 4.
> ```
> 
> `#`   Failed test 'js side error'
> `#`   at t/exception.t line 53.
> `#` Looks like you failed 1 test of 3.
> t/exception.t .. 
> Dubious, test returned 1 (wstat 256, 0x100)
> Failed 1/3 subtests 
>     `#` Failed to import cookie mojolicious
> t/session.t .... ok
> t/setup.t ...... ok
> t/synopsis.t ... ok
> ## Test Summary Report
> 
> t/exception.t (Wstat: 256 Tests: 3 Failed: 1)
>   Failed test:  2
>   Non-zero exit status: 1
> Files=5, Tests=12,  7 wallclock secs ( 0.06 usr  0.01 sys +  5.57 cusr  0.68 csys =  6.32 CPU)
> Result: FAIL
> -> FAIL Installing Mojo::Phantom failed. See /home/daniel/.cpanm/work/1464480846.2369/build.log for details. Retry with --force to force install it.

**Comment by dmanto** [comment]
add result with MOJO_PHANTOM_DEBUG
[s.txt](https://github.com/jberger/Mojo-Phantom/files/291426/s.txt)

**Comment by jberger** [comment]
the relevant portions of the log are:

```
  page.open('/', function(status) {

        perl('ok', 1, 'dummy test from javascript');
    page.evaluate(function(){
      window.dozNotExistz();
    });
    perl('fail', "don't get here");
;

    phantom.exit();
  });


Perl <<<< Phantom: ["ok",1,"dummy test from javascript"]
--MOJO_PHANTOM_MSG--


Perl <<<< Phantom: ["fail","don't get here"]
--MOJO_PHANTOM_MSG--


    #   Failed test 'don't get here'
    #   at (eval 94) line 1.
Stream for 5165 closed
Use of uninitialized value $error in scalar chomp at t/exception.t line 51.

    #   Failed test 'got the right error'
    #   at t/exception.t line 52.
    #                   undef
    #     doesn't match '(?^:PHANTOM ERROR.*dozNotExistz)'
    # Looks like you failed 2 tests of 4.

#   Failed test 'js side error'
#   at t/exception.t line 53.
```

**Comment by dmanto** [comment]
The problem could be identifyied as phantomjs version installed with apt-get. Installing the binary package directly from phantomjs.org solved the problem.

To test if your downladed version has the same problem, just unzip the attached file and run:

`$> phantomjs phantom_exception_test.js`

That should output:
`Ok, got exception`

Meaning that phantomjs was able to follow the "onError()" function ok.

[phantom_exception_test.zip](https://github.com/jberger/Mojo-Phantom/files/291858/phantom_exception_test.zip)

**Comment by jberger** [comment]
@dmanto filed a bug upstream at https://bugs.launchpad.net/ubuntu/+source/phantomjs/+bug/1587634
