### ISSUE TITLE
Mojo::Util::spurt deprecated in favor of Mojo::File::spurt

### ISSUE THREAD

**Issue by dmanto** [jberger/Mojo-Phantom#15]
In version 0.07, with Mojolicious v7.28, just running the code example shown in main page, you get:

`# Subtest: all phantom tests successful
Mojo::Util::spurt is DEPRECATED in favor of Mojo::File::spurt at /home/bam/.plenv/versions/5.24.1/lib/perl5/site_perl/5.24.1/Test/Mojo/Role/Phantom.pm line 47.
    ok 1 - name changed after loading
    1..1
ok 1 - all phantom tests successful
1..1
`

I think the deprecated code is in line 162 of lib/Mojo/Phantom.pm:

`Mojo::Util::spurt($js => "$tmp");`

**Comment by jberger** [comment]
Fixed in beb264d22a4fd2313c9c28537a6af7e00bd7035d

Thanks for the poke, I'm almost done with fixing up my modules affected by this deprecation.
